### ISSUE TITLE
Training Stops

### ISSUE THREAD

**Issue by naumanbashir70** [juntang-zhuang/LadderNet#16]
Hi, 

Could you help me. The training stops here. Please see attached image.
![ee](https://user-images.githubusercontent.com/58822992/83943195-780a3000-a813-11ea-91b9-c4468b4a6446.PNG)

**Comment by juntang-zhuang** [comment]
seems it's out of memory. Sorry, I have stopped maintaining this repo, and this repo is not optimized in terms of memory and dataloader stuff, and honestly it's not a good idea to load all dataset into memory, I did this mainly for simplicity (as is forked from other repo). I suggest using the model in this repo, and use streaming dataloaders, like here: https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader

**Comment by naumanbashir70** [comment]
Okay, 

Thanks  a lot.
