### ISSUE TITLE
Performance comparison with respect to parameter count

### ISSUE THREAD

**Issue by christian-steinmeyer** [juntang-zhuang/LadderNet#17]
Hi there! I've just come upon your LadderNet publication and was wondering whether you've also evaluated its performance with respect to the parameter counts. Especially, I'm interested if there is any benefit of using two U-Nets that are of depth `x` in a LadderNet architecture vs a single U-Net (with skip connections) that is of depth `2 * x`. As far as I understand, the amount of parameters should be roughly the same in both cases, correct? I could imagine both outcomes: The single U-Net performing better due to a bigger reception field or the LadderNet due to the additional paths. Do you have any data on that?

**Comment by juntang-zhuang** [comment]
Hi,  thanks for the comment, I did not try this idea on retina image dataset, but I performed similar comparison on natural image segmentation. Please see table 1 in https://openaccess.thecvf.com/content_ICCVW_2019/papers/CVRSUAD/Zhuang_ShelfNet_for_Fast_Semantic_Segmentation_ICCVW_2019_paper.pdf, and a GitHub repo https://github.com/juntang-zhuang/ShelfNet
