### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by LJM-GitHub** [juntang-zhuang/LadderNet#3]
Traceback (most recent call last):
  File "retinaNN_training.py", line 122, in <module>
    train_set = TrainDataset(patches_imgs_train[train_ind,...],patches_masks_train[train_ind,...])
MemoryError

What should I do? Thanks！

**Comment by juntang-zhuang** [comment]
Hi,
Thanks for your feedback.
Not sure what's the error. Try cleaning your GPU usage and memory, or try a smaller batchsize.

**Comment by LJM-GitHub** [comment]
Thanks,I try...

**Comment by whikwon** [comment]
For me, decreasing `N_subimgs` for CPU and `batch_size` for GPU worked.
