### ISSUE TITLE
error:  MemoryError: Unable to allocate 3.26 GiB for an array with shape (190000, 1, 48, 48) and data type float64

### ISSUE THREAD

**Issue by manvirvirk** [juntang-zhuang/LadderNet#7]
MemoryError: Unable to allocate 3.26 GiB for an array with shape (190000, 1, 48, 48) and data type float64
how to remove this error?

**Comment by juntang-zhuang** [comment]
Seems like your memory is not large enough. Try a small batchsize

**Comment by manvirvirk** [comment]
how to reduce batch size?

**Comment by yrgenkuci** [comment]
Open configuration.txt and play around with the "batch_size = 1024" or play around with the patches which are the "N_subims  = 190000" on the same file "configuration.txt". 

I hope that helps.
